// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxtbocefhzdozgbyasgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4dGJvY2VmaHpkb3pnYnlhc2d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzE5MTAsImV4cCI6MjA2Njg0NzkxMH0.Trg83c9XsZ78uJekXutfUfOBaKBxQtoMpwuA9fS1xmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});